### ISSUE TITLE
No issue just curious if foster has audio working

### ISSUE THREAD

**Issue by Gfunk117** [CM-Shield/android_device_nvidia_foster#1]
What is your progress on hdmi audio output for foster on cm-12.1/13?

**Comment by r3pwn** [comment]
I would assume it would, as the libaudio was distributed by Nvidia.

**Comment by r3pwn** [comment]
Oops, Nevermind, sister doesnt have a libaudio.

**Comment by r3pwn** [comment]
*foster

**Comment by webgeek1234** [comment]
It worked last test on cm-12.1. However, I'm having no end of troubles with CM 13 and the audio libs on Roth and the tablet, so I expect to have the same trouble here. But I can't test that until my RMA finishes. All I know right now is that CM 13 compiles for foster.
